### ISSUE TITLE
expanded-value

### ISSUE THREAD

**Issue by TomasTomecek** [bkabrda/dfe#3]
I got really confused with this one. I though it will expand a variable. I had to read the example to understand that

* I need to define the value in the top of a configuration
* I cannot use it as var
* it defaults to configuration name
* and seems like tag is a special, recognized value

**Comment by bkabrda** [comment]
So I renamed this to `config-value` in https://github.com/bkabrda/dfe/commit/49e56591f0353f4a845df9d63a23c37ed8f06057 and added help in https://github.com/bkabrda/dfe/commit/44d37bc16a6cde0c15738d708fefd52ece98c7ac. I think it should explain what/how this does - most of your points probably originate from lack of documentation. Could you check now and say whether everything's ok or if more improvements are still needed?

**Comment by TomasTomecek** [comment]
👍 just one nit, addressed in a pr
