### ISSUE TITLE
add a way to change name of dockerfile (path)

### ISSUE THREAD

**Issue by TomasTomecek** [bkabrda/dfe#7]
I don't want my template dockerfile being named `Dockerfile`.

**Comment by bkabrda** [comment]
I tried to explain this in the README file a bit more. The autovalues are only used unless these are found in `defaults` or `configurations`, so if you use

```
dockerfile:
  path: Dockerfile.whatever
```

either in `defaults` or in an item in `configurations`, that should do the trick. Feel free to reopen if this is still unclear or if it doesn't work as expected.
